# simple print
print("hello")
print("world")


# using end keyword
print("hello",end= '-')
print("world")


# printing different datatypes separated by commas
print("hii",8,8,9,True)


# using sep keyword
print("hii",8,8,9,True,sep= "/")


# type casting
x=str(6)
y=int(7.9)
z=float(6)
print(x,y,z)


# general Point - python allows you to assign values to multiple variables in one line 
x,y,z='apple','banana','orange'
print(x,y,z)


# one value to multiple variables
x=y=z=80
print(x,y,z)